/**
 * @fileoverview Rule to ensure AI-generated code has appropriate markers.
 * @author Jules
 */
"use strict";

const RULE_META = {
  type: "problem",
  docs: {
    description: "ensure AI-generated code is tagged with @ai-generated",
    category: "Governance",
    recommended: false,
  },
  messages: {
    missingMarker: "AI-generated code detected without @ai-generated marker. This decreases auditability.",
  },
};

const AI_PATTERNS = [
  /Generated by AI/i,
  /Synthesized by/i,
  /\/\/\s*@ai-generated/
];

function hasAiMarker(text) {
  return AI_PATTERNS.some(re => re.test(text));
}

function hasAssistantHint(text) {
  return /assistance|ai assistant|llm/i.test(text);
}

function shouldReportMissingMarker(text) {
  return !hasAiMarker(text) && hasAssistantHint(text);
}

function reportMissingMarker(context, node) {
  context.report({ node, messageId: "missingMarker" });
}

function create(context) {
  return {
    Program(node) {
      const text = context.getSourceCode().text;

      if (shouldReportMissingMarker(text)) {
        reportMissingMarker(context, node);
      }
    },
  };
}

module.exports = {
  meta: RULE_META,
  create,
};
