/**
 * @fileoverview Rule to ensure AI-generated code has appropriate markers.
 * @author Jules
 */
"use strict";

module.exports = {
  meta: {
    type: "problem",
    docs: {
      description: "ensure AI-generated code is tagged with @ai-generated",
      category: "Governance",
      recommended: false,
    },
    messages: {
      missingMarker: "AI-generated code detected without @ai-generated marker. This decreases auditability.",
    },
  },

  create(context) {
    // Heuristic: check for common AI-generated patterns if no marker exists
    const AI_PATTERNS = [
      /Generated by AI/i,
      /Synthesized by/i,
      /\/\/\s*@ai-generated/
    ];

    return {
      Program(node) {
        const sourceCode = context.getSourceCode();
        const text = sourceCode.text;
        const hasMarker = AI_PATTERNS.some(re => re.test(text));

        // This is a simplified rule: it warns if it *thinks* it's AI code but lacks the explicit marker.
        // For the prototype, we'll just check if the marker is missing in files that likely contain AI code.
        // In a real scenario, this would be integrated with the commit history or other signals.

        // For now, let's just report if @ai-generated is missing in any file (as a strict governance mode)
        if (!hasMarker) {
           // Only report if there's a hint of AI, or if we want to be strict.
           // Let's look for "Created with assistance" or similar.
           if (/assistance|ai assistant|llm/i.test(text)) {
             context.report({
               node,
               messageId: "missingMarker",
             });
           }
        }
      },
    };
  },
};
