// Ops & agent-tooling window manifests — terminals, schedulers, boards, and
// the agent-orchestration surfaces. Pure data: no logic lives here.
// Composed into WINDOW_MANIFESTS by src/lib/windowManifest.js.
// NOTE: `terminal` must stay first — window-lab defaults to WINDOW_MANIFESTS[0].

export const OPS_WINDOW_MANIFESTS = [
  {
    kind: 'terminal',
    canvasType: 'terminal',
    label: 'Terminal',
    componentName: 'TerminalWindow',
    componentPath: 'src/components/TerminalWindow.jsx',
    defaultSize: { w: 760, h: 480 },
    modeAvailability: { cloud_saas: false },
    launcher: { show: true, order: 60, icon: 'Terminal', label: 'Terminal', hint: 'WSL shell', props: { title: 'Terminal' } },
  },
  {
    kind: 'code_editor',
    canvasType: 'code_editor',
    label: 'Code Editor',
    componentName: 'CodeEditorWindow',
    componentPath: 'src/components/CodeEditorWindow.jsx',
    defaultSize: { w: 680, h: 480 },
    lab: {
      title: 'Code Editor',
      props: {
        code: "function helloHomebase() {\n  return 'Design safely first.';\n}\n",
      },
    },
  },
  {
    kind: 'scheduler',
    canvasType: 'scheduler',
    label: 'Scheduler',
    componentName: 'SchedulerWindow',
    componentPath: 'src/components/SchedulerWindow.jsx',
    defaultSize: { w: 760, h: 560 },
    launcher: { show: true, order: 90, icon: 'schedulerClock', label: 'Scheduler', hint: 'agent schedules', sizeOverride: { w: 760, h: 560 } },
  },
  {
    kind: 'julesTasks',
    canvasType: 'julesTasks',
    label: 'Jules Tasks',
    componentName: 'JulesTasksWindow',
    componentPath: 'src/components/JulesTasksWindow.jsx',
    defaultSize: { w: 520, h: 420 },
  },
  {
    kind: 'operationsBoard',
    canvasType: 'operationsBoard',
    label: 'Live Operations',
    componentName: 'OperationsBoardWindow',
    componentPath: 'src/components/OperationsBoardWindow.jsx',
    defaultSize: { w: 900, h: 620 },
    launcher: { show: true, order: 80, icon: 'Tools', label: 'Live operations', hint: 'runtime board', sizeOverride: { w: 900, h: 620 } },
  },
  {
    kind: 'rook',
    canvasType: 'rook',
    label: 'Rook Agent Control',
    componentName: 'RookWindow',
    componentPath: 'src/components/RookWindow.jsx',
    defaultSize: { w: 920, h: 650 },
    lab: { title: 'Rook Agent Control' },
  },
  {
    kind: 'sovereignTest',
    canvasType: 'sovereignTest',
    label: 'Sovereign Test',
    componentName: 'SovereignTestWindow',
    componentPath: 'src/components/SovereignTestWindow.jsx',
    defaultSize: { w: 500, h: 400 },
  },
  {
    kind: 'exoSkeleton',
    canvasType: 'exoSkeleton',
    label: 'ExoSkeleton',
    componentName: 'ExoSkeletonWindow',
    componentPath: 'src/components/ExoSkeletonWindow.jsx',
    defaultSize: { w: 700, h: 500 },
  },
  {
    kind: 'agentDesigner',
    canvasType: 'agentDesigner',
    label: 'Agent Designer',
    componentName: 'AgentDesignerWindow',
    componentPath: 'src/components/AgentDesignerWindow.jsx',
    defaultSize: { w: 1120, h: 700 },
  },
  {
    kind: 'overseer',
    canvasType: 'overseer',
    label: 'Overseer Watcher',
    componentName: 'OverseerWindow',
    componentPath: 'src/components/OverseerWindow.jsx',
    defaultSize: { w: 560, h: 460 },
    launcher: { show: true, order: 120, icon: 'Tools', label: 'Overseer Watcher', hint: 'repo auditor', sizeOverride: { w: 560, h: 460 } },
  },
  {
    kind: 'automation',
    canvasType: 'automation',
    label: 'Automation Board',
    componentName: 'AutomationWindow',
    componentPath: 'src/components/AutomationWindow.jsx',
    defaultSize: { w: 600, h: 500 },
    launcher: { show: true, order: 125, icon: 'Server', label: 'Automation', hint: 'manage running scripts', sizeOverride: { w: 600, h: 500 } },
  },
  {
    kind: 'vex',
    canvasType: 'vex',
    label: 'Vex Orchestrator',
    componentName: 'VexWindow',
    componentPath: 'src/components/VexWindow.jsx',
    defaultSize: { w: 560, h: 600 },
    modeAvailability: { cloud_saas: false },
  },
  {
    kind: 'registryTestWindow',
    canvasType: 'registryTestWindow',
    label: 'Registry Test Window',
    componentName: 'RegistryTestWindow',
    componentPath: 'src/components/RegistryTestWindow.jsx',
    defaultSize: { w: 400, h: 300 },
    launcher: { show: true, order: 130, icon: 'Tools', label: 'Registry Test Window', hint: 'test window' },
  },
  {
    kind: 'containers',
    canvasType: 'containers',
    label: 'Containers',
    componentName: 'ContainersWindow',
    componentPath: 'src/components/ContainersWindow.jsx',
    defaultSize: { w: 560, h: 460 },
    launcher: { show: true, order: 150, icon: 'Tools', label: 'Containers', hint: 'docker services' },
  },
  {
    kind: 'kubernetes',
    canvasType: 'kubernetes',
    label: 'Kubernetes',
    componentName: 'KubernetesWindow',
    componentPath: 'src/components/KubernetesWindow.jsx',
    defaultSize: { w: 720, h: 540 },
    launcher: { show: true, order: 170, icon: 'Tools', label: 'Kubernetes', hint: 'read-only cluster view' },
  },
];
