export function preserveSummary(existing) {
  if (!existing) return null;
  const m = existing.match(/## Summary\s*\n([\s\S]*?)(?=\n## )/);
  if (!m) return null;
  const body = m[1].trim();
  if (!body || body.startsWith('_')) return null;
  return body;
}

export function format({ project, treeStr, entries, summary, activity, kind }) {
  const lines = [];
  lines.push(`# ${project.name}`);
  lines.push('');
  lines.push(`**Owner:** ${project.owner_agent_id}`);
  if (kind === 'github' && project.repo) {
    lines.push(`**Repo:** https://github.com/${project.repo}`);
  } else if (project.path) {
    lines.push(`**Path:** \`${project.path}\``);
  }
  lines.push(`**Created:** ${new Date(project.created_at).toISOString().slice(0, 10)}`);
  lines.push(`**Brief refreshed:** ${new Date().toISOString().slice(0, 16).replace('T', ' ')}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(summary || '_No summary yet. The owner can fill this in or refresh after a meaningful change._');
  lines.push('');
  lines.push('## Directory layout');
  lines.push('');
  lines.push('```');
  lines.push(`${project.name}/`);
  lines.push((treeStr || '').trimEnd() || '(empty)');
  lines.push('```');
  lines.push('');
  lines.push('## Entry points');
  lines.push('');
  if (!entries || entries.length === 0) {
    lines.push('_None detected. Common patterns: `index.js`, `server.js`, `main.py`, a `package.json` `main` field._');
  } else {
    for (const e of entries) lines.push(`- **\`${e.file}\`** — ${e.why}`);
  }
  lines.push('');
  lines.push('## Recent activity');
  lines.push('');
  if (!activity || activity.length === 0) {
    lines.push('_No activity logged yet._');
  } else {
    for (const a of activity) {
      const stamp = new Date(a.created_at).toISOString().slice(0, 16).replace('T', ' ');
      const detail = a.detail ? `: ${a.detail}` : '';
      lines.push(`- ${stamp} — **${a.agent_id}** ${a.action}${detail}`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push('_Auto-generated by Censai. Use `refresh_brief` to regenerate after major changes._');
  lines.push('');
  return lines.join('\n');
}
