export const CHANGE_IMPACT_RULES = [
  {
    id: 'agent-tool',
    label: 'Agent tool',
    terms: ['tool', 'function calling', 'toolkit', 'tool kit', 'capability'],
    surfaces: [
      'server/tools/definitions/',
      'server/tools/handlers/',
      'server/tools/handlers/index.js',
      'server/tools/catalog.js',
      'server/tools/rbac/',
      'tests/integrity.test.js',
    ],
    checks: ['tool definition and handler both exist', 'permission filtering is preserved', 'catalog metadata is present'],
  },
  {
    id: 'window',
    label: 'Canvas window',
    terms: ['window', 'canvas app', 'launcher', 'tile', 'panel'],
    surfaces: [
      'src/lib/manifest/',
      'src/components/<Name>Window.jsx',
      'docs/WINDOW_INTEGRATION_SPEC.md',
    ],
    checks: ['one manifest entry only', 'component auto-wires', 'loading, empty, and error states', 'npm run window:validate'],
  },
  {
    id: 'provider-model',
    label: 'Model or provider',
    terms: ['provider', 'model', 'cohere', 'ollama', 'openrouter', 'gemini', 'moonshot'],
    surfaces: [
      'server/aiGateway/',
      'server/providers/registry.js',
      'src/components/agent/AgentData.js',
      'src/components/windows/agentDesigner/modelConfig.js',
      '.env.example',
    ],
    checks: ['model routing resolves provider credentials', 'both agent editors expose the option', 'BYOK policy remains enforced'],
  },
  {
    id: 'api-route',
    label: 'API contract',
    terms: ['api', 'endpoint', 'route', 'request', 'response'],
    surfaces: ['server/routes/', 'src/lib/api.js', 'tests/'],
    checks: ['route is registered', 'client method matches response shape', 'error and authorization behavior are tested'],
  },
  {
    id: 'database',
    label: 'Database and persistence',
    terms: ['database', 'postgres', 'table', 'column', 'migration', 'persist', 'schema'],
    surfaces: ['docker/*.sql', 'server/db.js', 'server/operational-intelligence/', 'tests/'],
    checks: ['migration ordering is safe', 'reads and writes agree on shape', 'rollback and existing data are considered'],
    risk: 'high',
  },
  {
    id: 'auth',
    label: 'Authentication and tenancy',
    terms: ['auth', 'login', 'session', 'oauth', 'permission', 'tenant', 'user role'],
    surfaces: ['server/routes/auth.js', 'server/security/', 'server/middleware/', 'tests/'],
    checks: ['unauthenticated and unauthorized paths differ', 'session ownership is preserved', 'no credentials enter logs or client state'],
    risk: 'high',
  },
  {
    id: 'chat-runtime',
    label: 'Chat and agent runtime',
    terms: ['chat', 'prompt', 'middleware', 'context', 'agent runtime', 'intercept'],
    surfaces: ['server/routes/chat/', 'server/aiGateway/', 'server/tools/', 'tests/'],
    checks: ['system context is bounded', 'tool permissions remain authoritative', 'streaming and non-streaming responses stay compatible'],
    risk: 'high',
  },
  {
    id: 'memory',
    label: 'Agent memory',
    terms: ['memory', 'recall', 'journal', 'knowledge graph', 'healing'],
    surfaces: ['server/memory/', 'server/memory.js', 'tests/memoryCore.test.js'],
    checks: ['private journal content stays redacted', 'retrieval degrades safely', 'prompt growth remains bounded'],
    risk: 'high',
  },
  {
    id: 'frontend-state',
    label: 'Canvas state',
    terms: ['workspace state', 'localstorage', 'zustand', 'canvas state', 'save layout'],
    surfaces: ['src/app/AppContent.jsx', 'src/lib/store.js', 'src/lib/agentStore.js'],
    checks: ['homebase.workspace.v1 remains compatible', 'state has a migration or safe default', 'reload behavior is tested'],
  },
  {
    id: 'styling',
    label: 'Interface styling',
    terms: ['style', 'css', 'theme', 'color', 'layout', 'design'],
    surfaces: ['src/components/', 'src/components/Theme.jsx'],
    checks: ['semantic theme variables are used', 'light and dark themes remain readable', 'layout works at narrow sizes'],
  },
];

